CREATE TABLE SALGRADE1 (
    GRADE INT PRIMARY KEY,
    LOSAL INT,
    HISAL INT
);

INSERT ALL
    INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (1, 700, 1200)
    INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (2, 1201, 1400)
    INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (3, 1401, 2000)
    INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (4, 2001, 3000)
    INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (5, 3001, 9999)
SELECT 1 FROM DUAL;

CREATE TABLE DEPTED (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(14),
    LOC VARCHAR(13)
);

INSERT ALL
      INTO DEPTED (DEPTNO, DNAME, LOC) VALUES (10, 'ACCOUNTING', 'NEW YORK')
      INTO DEPTED (DEPTNO, DNAME, LOC) VALUES (20, 'RESEARCH', 'DALLAS')
      INTO DEPTED (DEPTNO, DNAME, LOC) VALUES (30, 'SALES', 'CHICAGO')
      INTO DEPTED (DEPTNO, DNAME, LOC) VALUES (40, 'OPERATIONS', 'BOSTON')
SELECT 1 FROM DUAL;    

CREATE TABLE EMPLOY (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(10),
    JOB VARCHAR(9),
    MGR INT,
    HIREDATE DATE,
    SAL INT,
    COMM INT,
    DEPTNO INT
);

INSERT ALL
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7369, 'SMITH', 'CLERK', 7902, TO_DATE('17-DEC-1980', 'DD-MON-YYYY'), 800, NULL, 20)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('20-FEB-1981', 'DD-MON-YYYY'), 1600, 300, 30)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7521, 'WARD', 'SALESMAN', 7698, TO_DATE('22-FEB-1981', 'DD-MON-YYYY'), 1250, 500, 30)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7566, 'JONES', 'MANAGER', 7839, TO_DATE('02-APR-1981', 'DD-MON-YYYY'), 2975, NULL, 20)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7654, 'MARTIN', 'SALESMAN', 7698, TO_DATE('28-SEP-1981', 'DD-MON-YYYY'), 1250, 1400, 30)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7698, 'BLAKE', 'MANAGER', 7839, TO_DATE('01-MAY-1981', 'DD-MON-YYYY'), 2850, NULL, 30)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7782, 'CLARK', 'MANAGER', 7839, TO_DATE('09-JUN-1981', 'DD-MON-YYYY'), 2450, NULL, 10)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7788, 'SCOTT', 'ANALYST', 7566, TO_DATE('19-APR-1987', 'DD-MON-YYYY'), 3000, NULL, 20)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7839, 'KING', 'PRESIDENT', NULL, TO_DATE('17-NOV-1981', 'DD-MON-YYYY'), 5000, NULL, 10)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7844, 'TURNER', 'SALESMAN', 7698, TO_DATE('08-SEP-1981', 'DD-MON-YYYY'), 1500, 0, 30)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7876, 'ADAMS', 'CLERK', 7788, TO_DATE('23-JUL-1987', 'DD-MON-YYYY'), 1100, NULL, 20)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7900, 'JAMES', 'CLERK', 7698, TO_DATE('03-DEC-1981', 'DD-MON-YYYY'), 950, NULL, 30)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7902, 'FORD', 'ANALYST', 7566, TO_DATE('03-DEC-1981', 'DD-MON-YYYY'), 3000, NULL, 20)
    INTO EMPLOY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7934, 'MILLER', 'CLERK', 7782, TO_DATE('23-JAN-1982', 'DD-MON-YYYY'), 1300, NULL, 10)
SELECT 1 FROM DUAL;



--Q1. Select all information of various tables.
SELECT * FROM EMPLOY;
SELECT * FROM DEPTED;
SELECT * FROM SALGRADE1;

--Q2. See the structure of the above tables.
DESCRIBE SALGRADE1;
DESCRIBE EMPLOY;
DESCRIBE DEPTED;

--Q3.  List all information whose salary in between 1000 and 3000. Use EMP table.
SELECT * FROM EMPLOY
WHERE SAL BETWEEN 1000 AND 3000;

--Q4.  List name and salary only of employees. Use EMP table.
SELECT ENAME, SAL AS SALARY FROM EMPLOY;

--Q5.  List the above in sorted order. Sort by name. 
SELECT ENAME,SAL AS SALARY FROM EMPLOY ORDER BY ENAME ASC;

--Q6.  List all employee name and dept no who are in dept 10 and 30. Use EMP table.
SELECT ENAME , DEPTNO FROM EMPLOY
WHERE DEPTNO BETWEEN 10 AND 30;

--Q7.  List name ,job of all clerks in dept 20 . Use EMP table.
SELECT ENAME FROM EMPLOY
WHERE JOB = 'CLERK' AND DEPTNO = 20 ;

--Q8.  List name,job of all clerks in dept 20 and 30.
SELECT ENAME FROM EMPLOY
WHERE DEPTNO BETWEEN 20 AND 30;

--Q9.  Display all employees whose name starts with ‘S’.
SELECT ENAME FROM EMPLOY
WHERE ENAME LIKE 'S%';

--Q10. Display all employees whose name has four characters only.
SELECT ENAME FROM EMPLOY
WHERE ENAME LIKE '____';

--Q11.  Display all employees whose name ends with ‘L’.
SELECT ENAME FROM EMPLOY
WHERE ENAME LIKE '%L';

--Q12. List all employees who have a manager.
SELECT ENAME FROM EMPLOY
WHERE JOB = 'MANAGER';

--Q13. List all employees who do not have a manager
SELECT ENAME FROM EMPLOY
WHERE JOB != 'MANAGER';

--Q14.  List name and Total of salary i.e sal+commission.
SELECT ENAME , (SAL + NVL(COMM,0)) AS TOTAL_SAL FROM EMPLOY;
--Q15. List name and Annual Salary i.e sal*12.
SELECT ENAME , SAL*12 AS ANNUAL_SAL FROM EMPLOY;
--Q16.  List all employees who joind in the year 1981.
SELECT ENAME FROM EMPLOY
WHERE EXTRACT(YEAR FROM HIREDATE) = '1981';


--Q17. Display data as who , what ,when and how much display should look like:-

-- Eg: SMITH HAS HELD THE POSITION OF CLERK IN 
-- DEPARTMENT 20 SINCE ’12-OCT-1990’AND EARNS 1500. 
SELECT ENAME ||' HAS HELD THE POSITION OF '|| JOB ||' IN DEPARTMENT '|| DEPTNO ||' SINCE ' || HIREDATE ||' AND '||'EARN' || SAL ||'.'
FROM EMPLOY;

--Q18.  Supply values at runtime and display all employees in the user specified job title. 
ACCEPT USER_JOB_TITLE CHAR PROMPT 'Enter Job Title: '
SELECT ENAME FROM EMPLOY 
WHERE JOB = '&USER_JOB_TITLE';

--Q19. Find all employees joined on a specified date entered by the user.
ACCEPT USER_HIREDATE CHAR PROMPT 'Enter DATE (IN FORMAT DD-MON-YYYY): '
SELECT ENAME FROM EMPLOY
WHERE HIREDATE = TO_DATE('&USER_HIREDATE','DD-MON-YYYY');

--Q20.  Generate a query that accepts two dates i.e. the joining dates of EMP(range) at runtime and gives the output.
ACCEPT USER_START_DATE CHAR PROMPT 'Enter DATE (IN FORMAT DD-MON-YYYY): '
ACCEPT USER_END_DATE CHAR PROMPT 'Enter DATE (IN FORMAT DD-MON-YYYY): '
SELECT ENAME FROM EMPLOY
WHERE HIREDATE BETWEEN TO_DATE('&USER_START_DATE','DD-MON-YYYY') AND TO_DATE('&USER_END_DATE','DD-MON-YYYY');

--Q21.  Define one variable i.e the REM= ‘sal*12+NVL(comm.,0) Use the variable to find all employees who earn $10000 a year or more.
DEFINE REM = 'SAL*12 + NVL(COMM,0)'
SELECT * FROM EMPLOY
WHERE &REM >= 15000;

--Q22. . Create a EMP11 table which has the following fields 

-- Empno NUMBER(2) 
-- Ename VARCHAR2(25) 
-- Date_join DATE 
-- Deptno NUMBER(2) 
-- Salary NUMBER(10,2) 
-- Job VARCHAR2(10) 
-- Comm NUMBER(7,2)

CREATE TABLE EMP11 (
    EMPNO NUMBER(2),
    ENAME VARCHAR2(25),
    DATE_JOIN DATE,
    DEPTNO NUMBER(2),
    SALARY NUMBER(10,2),
    JOB VARCHAR2(10),
    COMM NUMBER(7,2)
)

--Q23. Create another table with the following constraints 
-- Empno NUMBER(2) 
-- Ename VARCHAR2(25) 
-- Date_join DATE 
-- Deptno NUMBER(2) 
-- Salary NUMBER(10,2) 
-- Job VARCHAR2(10) 
-- Comm NUMBER(7,2)

CREATE TABLE EMP_DETAILS (
    EMPNO NUMBER(2) PRIMARY KEY,  
    ENAME VARCHAR2(25) NOT NULL,  
    DATE_JOIN DATE NOT NULL,      
    DEPTNO NUMBER(2),             
    SALARY NUMBER(10,2) NOT NULL, 
    JOB VARCHAR2(10) NOT NULL,    
    COMM NUMBER(7,2)              
    );
--Q24.  Give different field names to the table. Create a table emp21 with only name, sal and job from employ.
CREATE TABLE EMP21 AS 
   SELECT ENAME AS NAME, SAL AS SALARY,JOB AS JOB_NAME FROM EMPLOY;
SELECT * FROM EMP21;



